
    
FROM python:3.8-slim

WORKDIR /app

ADD . /app

RUN apt-get update && apt-get install -y libgomp1

RUN pip install --upgrade pip

RUN pip --default-timeout=6000 install pycaret

RUN pip install -r requirements2.txt

EXPOSE 8007

CMD ["python", "fraud_voting_model_api_with_docker.py"]    
